backend:
  name: git-gateway
  branch: main 

media_folder: "static/uploads"  # Where uploaded images are stored
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/en/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}"}
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["research"]}
      - { label: "Content", name: "body", widget: "markdown" }
      

  - name: "projects"
    label: "Projects"
    folder: "content/en/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}"}
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Link", name: "link", widget: "string", required: false }

      - label: "Params"
        name: "params"
        widget: "object"
        fields:
          - label: "Button"
            name: "button"
            widget: "object"
            fields:
              - { label: "Icon", name: "icon", widget: "string", required: false }
              - { label: "Button Text", name: "btnText", widget: "string", required: false }
              - { label: "Button URL", name: "URL", widget: "string", required: false }

          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - { label: "Image Source", name: "src", widget: "image", required: false }
              - { label: "Image Scale", name: "scale", widget: "number", min: 0, max: 1, step: 0.1, value_type: "float", default: 0.5, required: false }

      - { label: "Content", name: "body", widget: "markdown", required: false }

  - name: "education"
    label: "Education"
    folder: "content/en/education"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}"}
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "University", name: "university", widget: "string", required: false  }
      - { label: "Degree", name: "degree", widget: "string", required: false  }
      - { label: "Year", name: "year", widget: "string" , required: false }

  - name: "experience"
    label: "Experience"
    folder: "content/en/experience"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false  }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}"}
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Job Title", name: "jobTitle", widget: "string", required: false  }
      - { label: "Company", name: "company", widget: "string" , required: false }
      - { label: "Location", name: "location", widget: "string" , required: false }
      - { label: "Duration", name: "duration", widget: "string" , required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }

  - name: "client-work"
    label: "Client Work"
    folder: "content/en/client-work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Client Logo", name: "params.logo.src", widget: "image" }
      - { label: "Logo Scale", name: "params.logo.scale", widget: "number", min: 0, max: 1, step: 0.1, default: 0.5 }

  - name: "publications"
    label: "Publications"
    folder: "content/en/publications"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}"}
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Button Text", name: "buttonText", widget: "string", default: "Full Text" }
      - { label: "Picture", name: "picture", widget: "image" }
      - { label: "Authors", name: "authors", widget: "string" }
      - { label: "Journal", name: "journal", widget: "string" }
      - { label: "Abstract", name: "abstract", widget: "text" }
      - { label: "DOI", name: "doi", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }

  - name: "press"
    label: "Press"
    folder: "content/en/press"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}"}
      - { label: "Link", name: "link", widget: "string", required: false}
      - { label: "Picture", name: "picture", widget: "image" }
      - { label: "Subtitle (source)", name: "source", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }