backend:
  name: auth0
  identity_url: "https://${AUTH0_DOMAIN}"
  domain: ${AUTH0_DOMAIN}
  client_id: ${AUTH0_CLIENT_ID}
  redirect_uri: https://emmayannzhang.me/admin/

media_folder: "static/images/uploads"  # Where uploaded images are stored
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Button Icon", name: "params.button.icon", widget: "string", default: "icon-arrow-right" }
      - { label: "Button Text", name: "params.button.btnText", widget: "string", default: "Case Study" }
      - { label: "Button URL", name: "params.button.URL", widget: "string" }
      - { label: "Project Image", name: "params.image.src", widget: "image" }
      - { label: "Image Scale", name: "params.image.scale", widget: "number", min: 0, max: 1, step: 0.1, default: 0.5 }

  - name: "education"
    label: "Education"
    folder: "content/education"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "University", name: "university", widget: "string" }
      - { label: "Degree", name: "degree", widget: "string" }
      - { label: "Year", name: "year", widget: "string" }

  - name: "experience"
    label: "Experience"
    folder: "content/experience"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Job Title", name: "jobTitle", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Duration", name: "duration", widget: "string" }

  - name: "client-work"
    label: "Client Work"
    folder: "content/client-work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Client Logo", name: "params.logo.src", widget: "image" }
      - { label: "Logo Scale", name: "params.logo.scale", widget: "number", min: 0, max: 1, step: 0.1, default: 0.5 }
